#!/bin/bash

SED=$(which sed);
GREP=$(which grep);

#
# This is an example of reset password hook in Jelastic
#

J_OPENSHIFT_APP_ADM_USER="cassandra";   ### Specify your admin user ###
#$J_OPENSHIFT_APP_ADM_USER              ;   ### The value of this variable is randomly generated and will be sent to a user by email

function _setPassword() {
	passwd_file=$(mktemp);
	cassanra_conf="/opt/repo/versions/1.2.5/conf/cassandra.yaml";
	cqlsh_app="/opt/repo/versions/1.2.5/bin/cqlsh";

	echo "ALTER USER cassandra WITH PASSWORD '$J_OPENSHIFT_APP_ADM_PASSWORD';" > $passwd_file;
    export CQLSH_HOST=$OPENSHIFT_CASSANDRA_DB_HOST;
    export CQLSH_PORT=$OPENSHIFT_CASSANDRA_DB_PORT;

	grep "^authenticator: org.apache.cassandra.auth.AllowAllAuthenticator" $cassanra_conf && {
        # initial start
        sleep 25; ### Cassandra service listeners are not ready to listen after the service been started, it need time
		[ -f "$passwd_file" ] && $cqlsh_app --file $passwd_file && return 0;
	} || {
		$SED -i 's/authenticator: org.apache.cassandra.auth.PasswordAuthenticator/authenticator: org.apache.cassandra.auth.AllowAllAuthenticator/g'	$cassanra_conf;
		service cartridge restart > /dev/null 2>&1;
        sleep 25; ### Cassandra service listeners are not ready to listen after the service been started, it need time
		[ -f "$passwd_file" ] && $cqlsh_app --file $passwd_file;
		$SED -i 's/authenticator: org.apache.cassandra.auth.AllowAllAuthenticator/authenticator: org.apache.cassandra.auth.PasswordAuthenticator/g'	$cassanra_conf;
		service cartridge restart > /dev/null 2>&1;
	}

}

